const ADD_SUCCESS = 'notes/ADD_SUCCESS';
const DELETE_SUCCESS = 'notes/DELETE_SUCCESS';
const UPDATE_SUCCESS = 'notes/UPDATE_SUCCESS';

const FETCH_REQUEST = 'notes/FETCH_REQUEST';
const FETCH_SUCCESS = 'notes/FETCH_SUCCESS';
const FETCH_ERROR = 'notes/FETCH_ERROR';

export default {
  ADD_SUCCESS,
  DELETE_SUCCESS,
  UPDATE_SUCCESS,

  FETCH_REQUEST,
  FETCH_SUCCESS,
  FETCH_ERROR,
};
